# Generated by Django 2.0.dev20170317003359 on 2017-05-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns_backend_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupchat_message', to='sns_backend_rest.GroupChatRoom'),
        ),
    ]
