# Generated by Django 2.0.dev20170317003359 on 2017-05-19 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sns_backend_rest', '0002_auto_20170520_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatroom',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
