# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_backend_rest', '0004_wall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='wall_posts', to='sns_backend_rest.Post'),
        ),
    ]
