# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-03 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns_backend_rest', '0011_auto_20170526_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='upload image'),
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='upload image'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
