# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sns_backend_rest', '0013_option_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_poll', to='sns_backend_rest.Poll'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
