# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sns_backend_rest', '0014_auto_20170609_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='poll_voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
