// general
export const SERVER_DOWN = "SERVER_DOWN"

// sign up
export const CHECK_USER = "CHECK_USER"
export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_OK = "SIGNUP_OK"
export const SIGNUP_FAILED = "SIGNUP_FAILED"
export const REFRESH = "REFRESH"
export const USER_EXISTS_YES = "USER_EXISTS_YES"
export const USER_EXISTS_NO = "USER_EXISTS_NO"

// profile images
export const IMAGE_LIST = "IMAGE_LIST"
export const GET_PROFILE_IMAGES = "GET_PROFILE_IMAGES"

// login
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const AUTH_OK = "AUTH_OK"
export const AUTH_FAILED = "AUTH_FAILED"
export const LOGOUT = "LOGOUT"

//update vote
export const UPDATE_VOTE = "UPDATE_VOTE"

//friend

export const FRIEND_REQEUSTS = "FRIEND_REQEUSTS"
export const MY_FRIENDS_LIST = "MY_FRIENDS_LIST"
export const GET_MY_FRIENDS = "GET_MY_FRIENDS"


// posts
export const GET_POSTS_WALL = "GET_POSTS_WALL"
export const GET_POSTS = "GET_POSTS"
export const GETPOSTS_FAILED = "GETPOSTS_FAILED"
export const POST_LIST = "POST_LIST"
export const POST_WALL_LIST ="POST_WALL_LIST"
export const POST_TEXT = "POST_TEXT"
export const DELETE_POST = "DELETE_POST";
export const REVISE_POST = "REVISE_POST";

// comments
export const GET_COMMENTS = "GET_COMMENTS"
export const GETCOMMENTS_FAILED = "GETCOMMENTS_FAILED"
export const COMMENT_LIST = "COMMENT_LIST"
export const POST_COMMENT = "POST_COMMENT"

// like
export const UPDATE_LIKE = "UPDATE_LIKE"
export const UPDATE_LIKE_COMMENT = "UPDATE_LIKE_COMMENT"
export const POST_EXISTS_NO = "POST_EXISTS_NO"
export const COMMENT_EXISTS_NO = "COMMENT_EXISTS_NO"

// chat
export const GET_USERS = "GET_USERS"
export const GETUSRES_FAILED = "GETUSERS_FAILED"
export const USER_LIST = "USER_LIST"
export const CHAT_START = "CHAT_START"
export const GETROOMS_FAILED = "GETROOMS_FAILED"
export const POSTROOM_FAILED = "POSTROOM_FAILED"
export const GET_MESSAGES = "GET_MESSAGES"
export const GETMESSAGES_FAILED = "GETMESSAGES_FAILED"
export const MESSAGE_LIST = "MESSAGE_LIST"
export const POST_MESSAGE = "POST_MESSAGE"
export const POSTMESSAGE_FAILED = "POSTMESSAGE_FAILED"
export const SET_PARTNER = "SET_PARTNER"
export const STOP_CHATTING =  "STOP_CHATTING"

// group chat
export const CREATE_GROUP = "CREATE_GROUP"
export const CREATEGROUP_FAILED = "CREATEGROUP_FAILED"
export const GET_GROUPS = "GET_GROUPS"
export const GETGROUPS_FAILED = "GETGROUPS_FAILED"
export const GROUP_LIST = "GROUP_LIST"
export const GROUPCHAT_START = "GROUPCHAT_START"
export const SET_GROUP = "SET_GROUP"
export const GET_GROUP_MESSAGES = "GET_GROUP_MESSAGES"
export const GROUP_MESSAGE_LIST = "GROUP_MESSAGE_LIST"
export const POST_GROUP_MESSAGE = "POST_GROUP_MESSAGE"
export const STOP_GROUP_CHATTING = "STOP_GROUP_CHATTING"
export const ADD_USER_GROUP = "ADD_USER_GROUP"
export const ADDUSERGROUP_FAILED = "ADDUSERGROUP_FAILED"
export const UPDATE_USERS = "UPDATE_USERS"

// settings
export const PROFILE_IMAGE_UPLOAD = "PROFILE_IMAGE_UPLOAD";
export const PROFILE_IMAGE_UPLOAD_SUCCESS = "PROFILE_IMAGE_UPLOAD_SUCCESS";
export const PROFILE_IMAGE_UPLOAD_FAIL = "PROFILE_IMAGE_UPLOAD_FAIL";
export const EMAIL_CHANGE = "EMAIL_CHANGE";
export const EMAIL_CHANGE_SUCCESS = "EMAIL_CHANGE_SUCCESS";
export const EMAIL_CHANGE_FAIL = "EMAIL_CHANGE_FAIL";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_FAIL = "PASSWORD_CHANGE_FAIL";
export const NSFW_DETECTED = "NSFW_DETECTED";
export const NSFW_DETECTED_CONFIRM = "NSFW_DETECTED_CONFIRM";

export const GPS_PARSE = "GPS_PARSE";


// search friends
export const SEARCH_FRIENDS = "SEARCH_FRIENDS";
export const SHOW_RESULT= "SHOW_RESULT";
export const SEARCH_RESULT_CLOSE = "SEARCH_RESULT_CLOSE";

// schedule
export const ADD_SCHEDULE = "ADD_SCHEDULE";
export const ADD_SHARE_SCHEDULE = "ADD_SHARE_SCHEDULE";
export const ADDSCHEDULE_FAILED = "ADDSCHEDULE_FAILED"
export const GET_SCHEDULES = "GET_SCHEDULES"
export const GETSCHEDULES_FAILED = "GETSCHEDULES_FAILED"
export const SCHEDULE_LIST = "SCHEDULE_LIST"
export const SELECT_FRIENDS = "SELECT_FRIENDS";
export const GET_SHARE_SCHEDULES = "GET_SHARE_SCHEDULES";
export const UPDATE_SHARE_SCHEDULES = "UPDATE_SHARE_SCHEDULES";
export const ACCEPT_SCHEDULE = "ACCEPT_SCHEDULE";
export const REJECT_SCHEDULE = "REJECT_SCHEDULE";
